import axios from 'axios';

export const GETSMURFS_START = 'GETSMURFS_START'
export const GETSMURFS_SUCCESS = 'GETSMURFS_SUCCESS'
export const GETSMURFS_FAILED = 'GETSURFS_FAILED'

export const ADDSMURF_START = 'ADDSMURF_START'
export const ADDSMURF_SUCCESS = 'ADDSMURF_SUCCESS'
export const ADDSMURF_FAILED = 'ADDSMURF_FAILED'


